name: aws_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/AmazonRootCA1.pem
  - assets/AmazonRootCA3.pem
  - assets/certificate.pem.crt
  - assets/private.pem.key
  - assets/public.pem.key
